"""Add consultation table

Revision ID: 0b4225988d7f
Revises: 9cd3f9275080
Create Date: 2025-10-14 00:54:28.905587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4225988d7f'
down_revision = '9cd3f9275080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('luts', sa.String(length=50), nullable=True),
    sa.Column('chronic_cough', sa.String(length=50), nullable=True),
    sa.Column('chronic_chest_pain', sa.String(length=50), nullable=True),
    sa.Column('chest_infection', sa.String(length=50), nullable=True),
    sa.Column('heart_dx', sa.String(length=50), nullable=True),
    sa.Column('palor', sa.String(length=50), nullable=True),
    sa.Column('jaundice', sa.String(length=50), nullable=True),
    sa.Column('murmur', sa.String(length=50), nullable=True),
    sa.Column('chest', sa.String(length=50), nullable=True),
    sa.Column('prostrate_specific_antigen', sa.String(length=50), nullable=True),
    sa.Column('psa_remark', sa.Text(), nullable=True),
    sa.Column('fbs', sa.String(length=50), nullable=True),
    sa.Column('rbs', sa.String(length=50), nullable=True),
    sa.Column('fbs_rbs_remark', sa.String(length=50), nullable=True),
    sa.Column('urine_analysis', sa.String(length=100), nullable=True),
    sa.Column('ua_remark', sa.String(length=50), nullable=True),
    sa.Column('diabetes_mellitus', sa.String(length=100), nullable=True),
    sa.Column('hypertension', sa.String(length=100), nullable=True),
    sa.Column('bp', sa.String(length=20), nullable=True),
    sa.Column('pulse', sa.String(length=20), nullable=True),
    sa.Column('spo2', sa.String(length=20), nullable=True),
    sa.Column('hs', sa.String(length=50), nullable=True),
    sa.Column('breast_exam', sa.String(length=50), nullable=True),
    sa.Column('breast_exam_remark', sa.Text(), nullable=True),
    sa.Column('abdomen', sa.String(length=50), nullable=True),
    sa.Column('assessment_hx_pe', sa.String(length=100), nullable=True),
    sa.Column('other_assessments', sa.Text(), nullable=True),
    sa.Column('overall_lab_remark', sa.Text(), nullable=True),
    sa.Column('other_remarks', sa.Text(), nullable=True),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=60),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    op.drop_table('consultation')
    # ### end Alembic commands ###
