"""Add doctor name and title to Branding

Revision ID: 0e44c08af759
Revises: 7df727399c6b
Create Date: 2025-10-17 18:58:33.243681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44c08af759'
down_revision = '7df727399c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('doctor_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding', schema=None) as batch_op:
        batch_op.drop_column('doctor_title')
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###
