"""Add registered_at to screeningbiodata

Revision ID: 37037a7efe63
Revises: fe7ae64f6441
Create Date: 2025-10-20 10:47:33.024275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37037a7efe63'
down_revision = 'fe7ae64f6441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_bio_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_bio_data', schema=None) as batch_op:
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###
