"""Add director_review_timestamp to Consultation

Revision ID: 478802299c6c
Revises: e30410aba93c
Create Date: 2025-10-17 18:33:19.906521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478802299c6c'
down_revision = 'e30410aba93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_review_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('director_review_timestamp')

    # ### end Alembic commands ###
