"""Add director comment fields to Consultation

Revision ID: 50fb980d5584
Revises: d44a6724548f
Create Date: 2025-10-14 09:46:28.229501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fb980d5584'
down_revision = 'd44a6724548f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_one', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_two', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_three', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_four', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('comment_four')
        batch_op.drop_column('comment_three')
        batch_op.drop_column('comment_two')
        batch_op.drop_column('comment_one')

    # ### end Alembic commands ###
