"""Add report_footer to Branding model

Revision ID: 7df727399c6b
Revises: 478802299c6c
Create Date: 2025-10-17 18:34:14.072337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df727399c6b'
down_revision = '478802299c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_footer', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding', schema=None) as batch_op:
        batch_op.drop_column('report_footer')

    # ### end Alembic commands ###
