"""Add user link to Patient model for account claiming

Revision ID: 9596641078c2
Revises: 96220fe5fff9
Create Date: 2025-10-17 10:26:15.642895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9596641078c2'
down_revision = '96220fe5fff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_patient_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_patient_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_patient_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
