"""Add user relationship to TemporaryAccessCode

Revision ID: 96220fe5fff9
Revises: e4c6c686fb29
Create Date: 2025-10-17 09:56:43.620726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96220fe5fff9'
down_revision = 'e4c6c686fb29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_access_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_temp_code_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_access_code', schema=None) as batch_op:
        batch_op.drop_constraint('fk_temp_code_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
