"""Add ScreeningBioData model

Revision ID: d44a6724548f
Revises: f4a8e09406b2
Create Date: 2025-10-14 08:45:29.131069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44a6724548f'
down_revision = 'f4a8e09406b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_bio_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_comprehensive_id', sa.Integer(), nullable=False),
    sa.Column('patient_id_for_year', sa.String(length=50), nullable=False),
    sa.Column('screening_year', sa.Integer(), nullable=False),
    sa.Column('company_section', sa.String(length=10), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_comprehensive_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_comprehensive_id', 'screening_year', 'company_section', name='_patient_comprehensive_year_company_uc'),
    sa.UniqueConstraint('patient_id_for_year', 'screening_year', 'company_section', name='_patient_id_year_company_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_bio_data')
    # ### end Alembic commands ###
