"""Add report_header and report_signature to Branding model

Revision ID: e30410aba93c
Revises: 9596641078c2
Create Date: 2025-10-17 13:10:29.357607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30410aba93c'
down_revision = '9596641078c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_header', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('report_signature', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding', schema=None) as batch_op:
        batch_op.drop_column('report_signature')
        batch_op.drop_column('report_header')

    # ### end Alembic commands ###
