"""Add Branding model

Revision ID: e4c6c686fb29
Revises: 87d1ceb9c7f6
Create Date: 2025-10-17 09:44:16.853212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c6c686fb29'
down_revision = '87d1ceb9c7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sa.String(length=100), nullable=False),
    sa.Column('logo_light', sa.String(length=255), nullable=True),
    sa.Column('logo_dark', sa.String(length=255), nullable=True),
    sa.Column('logo_home', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branding')
    # ### end Alembic commands ###
