"""Add 2FA fields to User model

Revision ID: ea61f0f32a6f
Revises: c6cbb37d0734
Create Date: 2025-10-16 06:52:48.693914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea61f0f32a6f'
down_revision = 'c6cbb37d0734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_enabled')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
