"""Add TemporaryAccessCode model

Revision ID: ee1f6586bc3f
Revises: 25e6c75ca498
Create Date: 2025-10-14 19:34:31.184938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1f6586bc3f'
down_revision = '25e6c75ca498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_access_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('use_type', sa.String(length=20), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_access_code')
    # ### end Alembic commands ###
